
all : bfs - program.c gcc - g - Wall - o a.out bfs -
      program.c
          bfs.c "../../../data-structures/linked-list/linked-list.c"
                "../../../data-structures/linked-list/queue.c" clean
    : $(RM) a.out